name: ecom_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  floating_bottom_navigation_bar: ^1.5.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  khalti_flutter: ^3.0.0
  lottie: ^2.6.0
  water_drop_nav_bar: ^2.2.1
  sliding_clipped_nav_bar: ^3.1.1
  carousel_slider: ^4.0.0
  simple_floating_bottom_nav_bar: ^0.0.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  intl: ^0.18.1
  flutter_pie_chart: ^0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
